import pool from '../config/db.js';


// ─── Insert Sale (sale_code auto generated by DB as S001, S002...) ────────────
export const insertSale = async (client, {
  business_id,
  product_id,
  total_quantity,
  out_mode_used,
}) => {
  const result = await client.query(
    `INSERT INTO sales
      (business_id, product_id, total_quantity, out_mode_used)
     VALUES ($1, $2, $3, $4)
     RETURNING *`,
    [business_id, product_id, total_quantity, out_mode_used]
  );
  return result.rows[0];
};

// ─── Insert Sale Item (one row per batch deducted) ────────────────────────────
export const insertSaleItem = async (client, {
  sale_id,
  batch_id,
  batch_no,
  quantity_deducted,
}) => {
  const result = await client.query(
    `INSERT INTO sale_items
      (sale_id, batch_id, batch_no, quantity_deducted)
     VALUES ($1, $2, $3, $4)
     RETURNING *`,
    [sale_id, batch_id, batch_no, quantity_deducted]
  );
  return result.rows[0];
};

// ─── Deduct Quantity from a Batch (inside transaction) ────────────────────────
export const deductBatchQuantity = async (client, batch_id, quantity_to_deduct) => {
  const result = await client.query(
    `UPDATE inventory_batches
     SET remaining_quantity = remaining_quantity - $1
     WHERE id = $2
       AND remaining_quantity >= $1
     RETURNING *`,
    [quantity_to_deduct, batch_id]
  );
  return result.rows[0];
};

// ─── Get Batches FIFO (oldest purchase_date first, has stock) ─────────────────
export const getBatchesFIFO = async (client, business_id, product_id) => {
  const result = await client.query(
    `SELECT * FROM inventory_batches
     WHERE business_id = $1
       AND product_id  = $2
       AND remaining_quantity > 0
     ORDER BY purchase_date ASC`,
    [business_id, product_id]
  );
  return result.rows;
};

// ─── Get Batches FEFO (earliest expiry first, skip expired, has stock) ─────────
export const getBatchesFEFO = async (client, business_id, product_id) => {
  const result = await client.query(
    `SELECT * FROM inventory_batches
     WHERE business_id = $1
       AND product_id  = $2
       AND remaining_quantity > 0
       AND (expiry_date IS NULL OR expiry_date > CURRENT_DATE)
     ORDER BY expiry_date ASC NULLS LAST`,
    [business_id, product_id]
  );
  return result.rows;
};

// ─── Get Single Batch for BATCH mode ─────────────────────────────────────────
export const getBatchByNo = async (client, business_id, product_id, batch_no) => {
  const result = await client.query(
    `SELECT * FROM inventory_batches
     WHERE business_id = $1
       AND product_id  = $2
       AND batch_no    = $3`,
    [business_id, product_id, batch_no]
  );
  return result.rows[0];
};

// ─── Get Sale by ID with deductions ──────────────────────────────────────────
export const getSaleById = async (sale_id) => {
  const sale = await pool.query(
    `SELECT * FROM sales WHERE id = $1`,
    [sale_id]
  );
  if (!sale.rows[0]) return null;

  const items = await pool.query(
    `SELECT batch_no, quantity_deducted AS quantity
     FROM sale_items WHERE sale_id = $1`,
    [sale_id]
  );

  return {
    ...sale.rows[0],
    deductions: items.rows,
  };
};

// ─── Get Sale by sale_code (e.g S001) ────────────────────────────────────────
export const getSaleBySaleCode = async (sale_code) => {
  const sale = await pool.query(
    `SELECT * FROM sales WHERE sale_code = $1`,
    [sale_code]
  );
  if (!sale.rows[0]) return null;

  const items = await pool.query(
    `SELECT batch_no, quantity_deducted AS quantity
     FROM sale_items WHERE sale_id = $1`,
    [sale.rows[0].id]
  );

  return {
    ...sale.rows[0],
    deductions: items.rows,
  };
};

// ─── Get All Sales by Business ────────────────────────────────────────────────
export const getSalesByBusiness = async (business_id) => {
  const result = await pool.query(
    `SELECT
       s.sale_code,
       s.id          AS sale_id,
       s.business_id,
       s.product_id,
       s.total_quantity,
       s.out_mode_used,
       s.created_at,
       JSON_AGG(
         JSON_BUILD_OBJECT(
           'batch_no', si.batch_no,
           'quantity', si.quantity_deducted
         ) ORDER BY si.created_at ASC
       ) AS deductions
     FROM sales s
     JOIN sale_items si ON si.sale_id = s.id
     WHERE s.business_id = $1
     GROUP BY s.id
     ORDER BY s.created_at DESC`,
    [business_id]
  );
  return result.rows;
};